"""Tests for parsing a PR-time adversarial-review comment (infra-commons/meta#1187).

`parse_review_comment` is the seam where prose written by one model becomes structured
findings this action files as issues. Everything that could quietly turn a real finding
into silence — or silence into a fabricated finding — is asserted here.

The two directions are not symmetric, and the tests reflect that:

  * A finding we cannot read must be COUNTED (`unparsed`) or reported as `drift`.
    Never dropped quietly — "no signal distinguishing 'no finding' from 'the model
    never ran'" is the exact complaint #1187 exists to answer, and rebuilding it
    inside the fix would be self-defeating.
  * A suppressed finding must be dropped ABSOLUTELY. Those entries were withheld at
    PR time against the suppressions file; re-filing one here would silently undo a
    decision a human already took.

The comment bodies below are assembled to match what adversarial-review.py actually
posts (marker, cache marker, heading, blockquote preamble, optional advisory note,
the mandated sections, then the suppressed-findings <details> block).
"""
import importlib.util
from pathlib import Path

_ACTION_DIR = Path(__file__).resolve().parent
_spec = importlib.util.spec_from_file_location("capture", _ACTION_DIR / "capture.py")
capture = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(capture)


_PREAMBLE = (
    "<!-- adversarial-review-bot -->\n"
    "<!-- cache-key: abc123 critical=false -->\n"
    "## Adversarial AI Security Review (Claude claude-sonnet-5)\n\n"
    "> **AI-generated by Claude claude-sonnet-5** — treat findings as a starting point.\n"
    "> Dismiss only after confirming a finding is mitigated or a false positive.\n"
    "> Commit: `deadbeef`\n\n"
)

_SUPPRESSED_BLOCK = (
    "\n\n---\n"
    "<details>\n"
    "<summary>Suppressed findings (acknowledged false positives)</summary>\n\n"
    "- ~~- [infra/main.tf:12] Terraform state may contain secrets.~~\n"
    "  **Suppressed** (`tf-state-secrets`): Documented false positive.\n\n"
    "</details>"
)


def _body(sections: str, *, preamble: str = _PREAMBLE, suppressed: bool = True) -> str:
    return preamble + "## Security findings\n\n" + sections + (_SUPPRESSED_BLOCK if suppressed else "")


_FULL_SECTIONS = (
    "### CRITICAL — exploit-ready, must fix before merge\n"
    '_(or "None")_\n\n'
    "### HIGH — serious, must fix before production\n"
    "- [.github/workflows/migrate-production.yml:65] `D1_PRODUCTION_TOKEN` is exposed to "
    "`npm ci`. A malicious postinstall script could exfiltrate it.\n"
    "- [src/lib/server/macros.ts:541] Hard reference with no schema fallback.\n\n"
    "### MEDIUM — fix within 90 days\n"
    "- [src/routes/api/+server.ts:20] Missing rate limit on the public endpoint.\n\n"
    "### LOW — best-practice improvements\n"
    "None\n\n"
    "### Summary\n"
    "Overall risk is moderate. The single most important thing to fix is the "
    "production token exposure at line 65.\n"
)


def _sev_map(result):
    return sorted((f["severity"], f["location"]) for f in result["findings"])


# ── The happy path ──────────────────────────────────────────────────────────────

def test_sections_map_to_severities():
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    assert result["status"] == "parsed"
    assert result["unparsed"] == 0
    assert _sev_map(result) == [
        ("HIGH", ".github/workflows/migrate-production.yml:65"),
        ("HIGH", "src/lib/server/macros.ts:541"),
        ("MEDIUM", "src/routes/api/+server.ts:20"),
    ]


def test_none_placeholders_yield_no_findings():
    """Both empty-section forms the system prompt produces must file nothing.

    `_(or "None")_` is the literal placeholder; a bare `None` is what the models
    actually tend to emit. Either one read as a finding would file an issue against a
    section that explicitly reported nothing.
    """
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    assert not [f for f in result["findings"] if f["severity"] in ("CRITICAL", "LOW")]


def test_summary_prose_is_not_parsed_as_findings():
    """### Summary terminates the last findings section.

    Its paragraph names a file and a line number, so a parser that ran to end-of-body
    would file the summary itself as a LOW finding.
    """
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    assert all("Overall risk" not in f["description"] for f in result["findings"])


def test_preamble_blockquote_and_commit_line_are_not_findings():
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    assert all("AI-generated" not in f["description"] for f in result["findings"])
    assert result["head_sha"] == "deadbeef"


def test_advisory_note_does_not_become_a_finding():
    preamble = _PREAMBLE + (
        "> ⚠️ **Advisory only — this review is not blocking merge.** No changed file "
        "touches a high-risk path.\n\n"
    )
    result = capture.parse_review_comment(_body(_FULL_SECTIONS, preamble=preamble), "Claude")
    assert all("Advisory only" not in f["description"] for f in result["findings"])


# ── Suppressed findings must never come back ────────────────────────────────────

def test_suppressed_block_is_not_ingested():
    """The single most important assertion in this file.

    The reviewer already withheld this finding at PR time by matching it against the
    suppressions file. Re-filing it post-merge through the new door would silently
    reverse a decision a human took, and would do so on every subsequent merge.
    """
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    assert all("main.tf" not in f["location"] for f in result["findings"])
    assert all("Terraform state" not in f["description"] for f in result["findings"])


def test_struck_bullet_above_the_block_is_still_dropped():
    """Belt-and-braces: a `~~struck~~` bullet is dropped even outside the <details>."""
    sections = (
        "### HIGH — serious\n"
        "- ~~- [infra/main.tf:12] Suppressed at PR time.~~\n"
        "- [src/app.py:4] A real one.\n\n"
        "### Summary\nFine.\n"
    )
    result = capture.parse_review_comment(_body(sections, suppressed=False), "Claude")
    assert [f["location"] for f in result["findings"]] == ["src/app.py:4"]


# ── Degradation must be loud ────────────────────────────────────────────────────

def test_marker_without_findings_section_is_drift_not_silence():
    """Format drift must never read as "the reviewer found nothing"."""
    body = _PREAMBLE + "The diff looked fine to me overall.\n"
    result = capture.parse_review_comment(body, "OpenAI")
    assert result["status"] == "drift"
    assert result["findings"] == []


def test_missing_anchor_but_present_sections_still_parses():
    """A dropped `## Security findings` line alone is recoverable, and recovered.

    Declaring drift here would discard readable findings over a cosmetic omission.
    """
    body = _PREAMBLE + _FULL_SECTIONS
    result = capture.parse_review_comment(body, "OpenAI")
    assert result["status"] == "parsed"
    assert len(result["findings"]) == 3


def test_infra_warning_is_skipped_not_drift():
    """A reviewer reporting itself skipped is a distinct, non-alarming state.

    It still matters — that PR merged with no review from this provider — but it is
    not evidence the output format broke, and conflating the two would make real
    drift harder to see.
    """
    body = (
        "<!-- adversarial-review-openai-bot -->\n"
        "## Adversarial AI Security Review (OpenAI gpt-5.6-terra) (skipped: quota exhausted)\n\n"
        "The provider account is out of quota.\n"
    )
    result = capture.parse_review_comment(body, "OpenAI")
    assert result["status"] == "skipped-infra"
    assert result["findings"] == []


def test_unreadable_bullet_is_counted_not_filed():
    sections = (
        "### HIGH — serious\n"
        "- something went wrong here with no file reference at all\n"
        "- [src/app.py:4] A readable one.\n\n"
        "### Summary\nFine.\n"
    )
    result = capture.parse_review_comment(_body(sections, suppressed=False), "Claude")
    assert result["unparsed"] == 1
    assert [f["location"] for f in result["findings"]] == ["src/app.py:4"]


# ── Field derivation ────────────────────────────────────────────────────────────

def test_title_is_the_first_sentence_and_bounded():
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    finding = next(f for f in result["findings"] if "migrate-production" in f["location"])
    assert finding["title"].startswith("&#96;D1_PRODUCTION_TOKEN&#96; is exposed")
    assert "postinstall" not in finding["title"]      # second sentence stays out of the title
    assert "postinstall" in finding["description"]    # but is kept in the body
    assert len(finding["title"]) <= 240


def test_relaxed_bullet_form_is_recovered():
    """A reviewer that drops the brackets but still names the file first is readable."""
    sections = (
        "### HIGH — serious\n"
        "- **src/lib/auth.ts:88** — Session token compared with `==`.\n\n"
        "### Summary\nFine.\n"
    )
    result = capture.parse_review_comment(_body(sections, suppressed=False), "Claude")
    assert result["unparsed"] == 0
    assert [f["location"] for f in result["findings"]] == ["src/lib/auth.ts:88"]


def test_continuation_lines_extend_the_description():
    sections = (
        "### HIGH — serious\n"
        "- [src/app.py:4] First line of the finding.\n"
        "  Continued detail on the next line.\n\n"
        "### Summary\nFine.\n"
    )
    result = capture.parse_review_comment(_body(sections, suppressed=False), "Claude")
    assert "Continued detail" in result["findings"][0]["description"]


def test_table_rows_are_not_parsed_as_findings():
    sections = (
        "### HIGH — serious\n"
        "| file | note |\n"
        "| --- | --- |\n"
        "| src/app.py | something |\n"
        "- [src/app.py:4] The actual finding.\n\n"
        "### Summary\nFine.\n"
    )
    result = capture.parse_review_comment(_body(sections, suppressed=False), "Claude")
    assert [f["location"] for f in result["findings"]] == ["src/app.py:4"]


def test_findings_are_sanitised():
    """Reviewer prose is untrusted text heading for a GitHub issue body."""
    sections = (
        "### HIGH — serious\n"
        "- [src/app.py:4] Mentions @someone and a ${{ secrets.FOO }} expression.\n\n"
        "### Summary\nFine.\n"
    )
    result = capture.parse_review_comment(_body(sections, suppressed=False), "Claude")
    desc = result["findings"][0]["description"]
    assert "@someone" not in desc
    assert "${{" not in desc


def test_category_is_unknown_for_ingested_findings():
    """A PR-time bullet carries no category; is_suppressed() depends on this value."""
    result = capture.parse_review_comment(_body(_FULL_SECTIONS), "Claude")
    assert {f["category"] for f in result["findings"]} == {"unknown"}
